name: Code Quality Check

on:
  pull_request:
    branches: [main]

jobs:
  format:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    # Don't block merge on failure - this is educational
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "18"

      - name: Check code formatting with Prettier
        run: npx prettier --check '**/*.{html,css,js,md,json}' --ignore-path .gitignore
        continue-on-error: true

      - name: Check JavaScript with ESLint
        run: npx eslint '**/*.js' --ignore-pattern 'node_modules/**'
        continue-on-error: true

      - name: Quality check summary
        if: always()
        run: |
          echo "💡 Code quality check complete!"
          echo "If issues were found, fix them locally:"
          echo "  - Format code: npm run format"
          echo "  - Check linting: npm run lint"
          exit 0
